activation: relu
batch_size: 16
dims: 140
direction: maximize
dropout: null
eval_metric: val_accuracy
exp_id: own_original_comp_bal_ss
learning_rate: 0.0026391989268866535
max_epochs: 3
mode: vanilla
momentum: 0.7973692426649911
n_units_l1: 20
n_units_l2: 14
n_units_l3: 14
negative_slope: null
nesterov: true
now: '202312191827'
num_hidden_layers: 3
num_workers: 2
optim: sgd
patience: 1
version: 0
