activation: leaky_relu
b1: 0.7130734087279957
b2: 0.42127393936307145
batch_size: 8
dims: 140
direction: minimize
dropout: null
eval_metric: rps
exp_id: own_original_comp_bal_fac_ss_rps_batch
learning_rate: 0.03911230572746575
max_epochs: 10
mode: vanilla
n_units_l1: 29
n_units_l2: 10
n_units_l3: 3
negative_slope: 0.09984761671029503
now: '202405261606'
num_hidden_layers: 3
num_workers: 2
optim: adam
patience: 15
version: 0
