activation: selu
batch_size: 8
dims: 140
direction: maximize
dropout: 0.24772770552143397
eval_metric: val_accuracy
exp_id: own_original_comp_bal_ss
learning_rate: 0.0012674214001131884
max_epochs: 1
mode: dropout
momentum: 0.004668744298109315
n_units_l1: 21
n_units_l2: 5
n_units_l3: 14
n_units_l4: 19
n_units_l5: 20
negative_slope: null
nesterov: true
now: '202311272207'
num_hidden_layers: 5
num_workers: 2
optim: sgd
patience: 2
version: 0
