activation: leaky_relu
b1: 0.7435022403989783
b2: 0.5055434950477113
batch_size: 8
dims: 140
direction: maximize
dropout: null
eval_metric: val_accuracy
exp_id: own_original_comp_bal_ss
learning_rate: 0.003087822832692537
max_epochs: 1
mode: vanilla
n_units_l1: 8
negative_slope: 0.055139885373200304
now: '202311272144'
num_hidden_layers: 1
num_workers: 2
optim: adam
patience: 2
version: 0
