activation: relu
batch_size: 8
dims: 140
direction: maximize
dropout: 0.5813207093771647
eval_metric: val_accuracy
exp_id: own_original_comp_bal_ss
learning_rate: 0.12009594050676681
max_epochs: 1
mode: dropout
momentum: 0.0012441535854751122
n_units_l1: 30
n_units_l2: 17
n_units_l3: 21
n_units_l4: 22
negative_slope: null
nesterov: false
now: '202311272212'
num_hidden_layers: 4
num_workers: 2
optim: sgd
patience: 2
version: 0
