experiment: own_original
experiment_id: own_original_comp_bal_ss_batch
description: "replica batch de los experimentos de mi Tésis"
enable: True
variables: &variables
  # _aux_: 0
  select: 32
data:
  <<: *variables
  aggregations:
    Points: mean
    FTG: mean
    FTG_rival: mean
    S: mean
    ST: mean
    F: mean
    C: mean
    Y: mean
    R: mean
    # O: mean
    # HW: mean
    Side: mean
  features:
    - 4
    - 30 # el maximo no puede superior al numero de samples
  leagues:
    -
  lags:
    - 15D
    - 30D
    - 60D
    - 180D
    - 365D
    - 730D
    - 1825D
  min_samples:
    - 1
    - 2
    - 2
    - 8
    - 10
    - 15
    - 15
  col_group: 
    - "idTeam"
  col_window: "Date"
  balance: True
  factor: True
  sample: "sequential"
  val_date: "2017-01-01"
paths:
  data: "datasets/data_train/data_"
  raw_data: "datasets/raw_datasets/datalake.csv"
  dtypes_path: "datasets/raw_datasets/dtypes.json"
training:
  <<: *variables
  max_epochs: 2
  patience: 1
  iterations: 2
  timeout: 1440      # in mins
  direction: "maximize"
  eval_metric: "val_accuracy"
  batch_size: 
    # - 8
    - 16
    # - 32
    # - 64
    # - 128
    # - 256