activation: leaky_relu
b1: 0.6188882641848806
b2: 0.948871452958436
batch_size: 8
dims: 140
direction: maximize
dropout: null
eval_metric: val_accuracy
exp_id: own_original_comp_bal_ss
learning_rate: 0.23564074664473406
max_epochs: 1
mode: batchnorm
n_units_l1: 21
n_units_l2: 30
n_units_l3: 21
n_units_l4: 15
n_units_l5: 16
negative_slope: 0.09889835323921248
now: '202311272139'
num_hidden_layers: 5
num_workers: 2
optim: adam
patience: 2
version: 0
