activation: selu
b1: 0.6782520674158329
b2: 0.851874280513975
batch_size: 8
dims: 140
direction: maximize
dropout: 0.12401174516620538
eval_metric: val_accuracy
exp_id: own_original_comp_bal_ss
learning_rate: 0.023669006828166177
max_epochs: 10
mode: dropout
n_units_l1: 7
n_units_l2: 15
n_units_l3: 14
n_units_l4: 23
negative_slope: null
now: '202311272110'
num_hidden_layers: 4
num_workers: 2
optim: adam
patience: 2
version: 0
