activation: selu
b1: 0.49575100161868263
b2: 0.9444399408104934
batch_size: 16
dims: 163
direction: maximize
dropout: null
eval_metric: val_accuracy
exp_id: own_top1_comp_fac_ss_batch
learning_rate: 0.2421140169852432
max_epochs: 2
mode: batchnorm
n_units_l1: 6
n_units_l2: 9
n_units_l3: 20
negative_slope: null
now: '202405022335'
num_hidden_layers: 3
num_workers: 2
optim: adam
patience: 15
version: 0
