activation: leaky_relu
b1: 0.947729239057137
b2: 0.4235069824242508
batch_size: 16
dims: 25
direction: maximize
dropout: null
eval_metric: val_accuracy
exp_id: own_original_comp_bal_ss_batch
learning_rate: 0.08016135976277561
max_epochs: 2
mode: vanilla
n_units_l1: 18
n_units_l2: 14
n_units_l3: 3
n_units_l4: 10
negative_slope: 0.06528609343937201
now: '202401201453'
num_hidden_layers: 4
num_workers: 2
optim: adam
patience: 1
version: 0
