activation: relu
batch_size: 8
dims: 140
direction: maximize
dropout: null
eval_metric: val_accuracy
exp_id: own_original_comp_bal_ss
learning_rate: 0.009165812459019745
max_epochs: 10
mode: batchnorm
momentum: 0.031003909229581038
n_units_l1: 17
negative_slope: null
nesterov: false
now: '202311271951'
num_hidden_layers: 1
num_workers: 2
optim: sgd
patience: 2
version: 0
